// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2vgUVp9UxUb4qsLOJfJu-rhB3LFMxX4',
    appId: '1:547250713887:web:1c6a73221ef42d91692c2a',
    messagingSenderId: '547250713887',
    projectId: 'fir-flutter-ubersorta',
    authDomain: 'fir-flutter-ubersorta.firebaseapp.com',
    storageBucket: 'fir-flutter-ubersorta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5NJLjMvdC-ZCLAJBxt9Jglq3uE3RvH4',
    appId: '1:547250713887:android:9aadcf4bf42568d8692c2a',
    messagingSenderId: '547250713887',
    projectId: 'fir-flutter-ubersorta',
    storageBucket: 'fir-flutter-ubersorta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5z3lpl6jSxYH_gU64j7umtqYjxpUQW0',
    appId: '1:547250713887:ios:02bc60ab1ff4be9f692c2a',
    messagingSenderId: '547250713887',
    projectId: 'fir-flutter-ubersorta',
    storageBucket: 'fir-flutter-ubersorta.appspot.com',
    iosClientId: '547250713887-o9vteu6gvugghiigt02aqr7spbfd9ntj.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5z3lpl6jSxYH_gU64j7umtqYjxpUQW0',
    appId: '1:547250713887:ios:02bc60ab1ff4be9f692c2a',
    messagingSenderId: '547250713887',
    projectId: 'fir-flutter-ubersorta',
    storageBucket: 'fir-flutter-ubersorta.appspot.com',
    iosClientId: '547250713887-o9vteu6gvugghiigt02aqr7spbfd9ntj.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
